version: '3.7'
services:
  app:
    container_name: guidelk-docker
    image: guidelk-docker
    build: ./
    ports:
      - "8085:8085"
    depends_on:
      - pg
  pg:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=guidelanka
